# -*- coding: utf-8 -*-
"""untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Nomandiu/894cb9a347e2bdb4207808c5489f2b2d/untitled0.ipynb
"""

'data science'

a=10
b=5
c=a+b
print(c)